# Generated by Django 5.2.6 on 2025-10-21 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ce champs ne doit contenir que des lettres et des chiffres', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
