# Generated by Django 5.2.6 on 2025-10-21 19:14

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='ens_date',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'description trop court !')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keyswords',
            field=models.TextField(validators=[ConferenceApp.models.validate_max_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(default=ConferenceApp.models.generate_submission_id, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
